notes/blog/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.home, name="Blog"),
]

notes/catalog/urls.py
from django.urls import path
from . import views

app_name = "catalog"

urlpatterns = [
    path("<slug:category_slug>", views.index, name="index"),
    path("product/<slug:product_slug>", views.detail_product, name="detail"),
    # path("catalog/<int:year>/<int:month>/<slug:slug>/", views.article_detail),
]

notes/main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
]

notes/settings/urls.py
from django.contrib import admin
from django.urls import path, include, URLResolver
from django.conf.urls.static import static
from django.conf import settings

from settings.settings import DEBUG

urlpatterns: list[URLResolver] = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("catalog/", include("catalog.urls", namespace="catalog")),
    path("blog/", include("blog.urls")),
]

if DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),

    ] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

notes/blog/models.py
from django.db import models

notes/catalog/models.py
from typing import Any
from django.db import models


class Categories(models.Model):
    name: str = models.CharField(
        verbose_name="Назва категорії", max_length=250, unique=True
    )
    slug: str = models.SlugField(
        verbose_name="Посилання slug",
        max_length=150,
        unique=True,
        blank=True,
        null=True,
    )

    class Meta:
        db_table: str = "category"
        verbose_name_plural: str = "Категорії"
        verbose_name: str = "Категорію"

    def __str__(self):
        return self.name


class Products(models.Model):
    name: str = models.CharField(
        verbose_name="Назва товару", max_length=250, unique=True
    )
    slug: str = models.SlugField(
        verbose_name="Посилання slug",
        max_length=150,
        unique=True,
        blank=True,
        null=True,
    )
    price: float = models.DecimalField(
        decimal_places=2, max_digits=7, default=0.00, verbose_name="Ціна"
    )
    discount: float = models.DecimalField(
        decimal_places=2, max_digits=7, default=0.00, verbose_name="Скідка"
    )
    quantity: int = models.PositiveIntegerField(default=0, verbose_name="Кількість")
    description: str = models.TextField(blank=True, null=True, verbose_name="Опис")
    categories = models.ForeignKey(
        to=Categories, on_delete=models.PROTECT, verbose_name="Категорія"
    )
    # categories: models.ForeignKey(
    #     to=Categories, on_delete=models.CASCADE, verbose_name="Категорія"
    # )
    # categories: models.ForeignKey(
    #     to=Categories, on_delete=models.SET_DEFAULT, default="Різне", verbose_name="Категорія"
    # )
    image = models.ImageField(
        upload_to="product_images", blank=True, null=True, verbose_name="Зображення"
    )

    class Meta:
        """Change admin console"""

        db_table: str = "product"
        verbose_name_plural: str = "Товари"
        verbose_name: str = "Товар"

    def __str__(self):
        """Reload method __str__"""
        return self.name

    def display_id(self):
        return f"{self.id:05}"

    def sell_price(self):
        if not self.discount:
            return self.price
        return round(self.price - (self.price * self.discount / 100), 2)

notes/main/models.py
from django.db import models

# Create your models here.

notes/blog/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.


def home(request):
    return HttpResponse('Hello World!')

notes/catalog/views.py
from django.shortcuts import render, get_list_or_404

from catalog.models import Products

# Create your views here.


def index(requests, category_slug):
    if category_slug == "vsi-tovari":
        items = Products.objects.all()
    else:
        items = get_list_or_404(Products.objects.filter(categories__slug=category_slug))

    context: dict[str : int | str] = {
        "title": "Каталог интернет магазина мебели",
        "content": "Новинки только у нас",
        "items": items,
    }
    return render(requests, "catalog/shop.html", context=context)


def detail_product(requests, product_slug):
    product = Products.objects.get(slug=product_slug)
    return render(requests, "catalog/product.html", context={"product": product})

notes/main/views.py
from django.http import HttpResponse
from django.shortcuts import render

from catalog.models import Categories


# Create your views here.


def index(request) -> HttpResponse:
    context: dict[str : int | str] = {
        "title": "Интернет магазин мебели",
        "content": "Современный интерьер",
    }
    return render(request, "main/index.html", context=context)


def about(request) -> HttpResponse:
    context: dict[str : int | str] = {
        "title": "О нас",
        "content": "Современный интерьер",
    }
    return render(request, "main/about.html", context=context)

notes/catalog/templates/catalog/product.html
{% extends "main/base.html" %}
{% load static  %}


 {% block title %}
		<title> {{ title }} </title>
    {% endblock %}



{% block header %}


		<!-- Start Hero Section -->
			<div class="hero">
				<div class="container">
					<div class="row justify-content-between">
						<div class="col-lg-5">
							<div class="intro-excerpt">
								<h1>{{ product.name }}</h1>
								<p class="mb-4">Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate velit imperdiet dolor tempor tristique.</p>
								<p><a href="" class="btn btn-secondary me-2">Shop Now</a><a href="#" class="btn btn-white-outline">Explore</a></p>
							</div>
						</div>
						<div class="col-lg-7">
{#							<div class="hero-img-wrap">#}
{#								<img src={% static "main/images/couch.png" %} class="img-fluid">#}
{#							</div>#}
						</div>
					</div>
				</div>
			</div>
		<!-- End Hero Section -->

{% endblock %}



		
{% block content %}

<div class="container">
    <div class="card" style="top: 125px; margin-bottom: 450px;">
{#        <div class="d-inline-flex p-2 bd-highlight">#}
            <div class="d-flex justify-content-center">
       <img src="{{ product.image.url }}" style="width: 400px;" alt="{{product.name}}">
            </div>
{#        </div>#}
        <div class="card-body">
            <h1 class="display-4 fw-normal text-center ">{{ product.name}}</h1>
            <p class="product-item text-center"> Код товара - {{ product.display_id }}</p>
            <h2><p class="text-start">{{ product.description }}</p></h2>
            <a href="#" class="btn btn-primary">Купить по цене {{ product.sell_price }}$</a>
         </div>
    </div>
</div>


{% endblock %}

notes/catalog/templates/catalog/shop.html
{% extends "main/base.html" %}
{% load static  %}


  {% block title %}
		<title> {{ title }} </title>
    {% endblock %}
{% block header %}

		<!-- Start Hero Section -->
			<div class="hero">
				<div class="container">
					<div class="row justify-content-between">
						<div class="col-lg-5">
							<div class="intro-excerpt">
								<h1>{{ content }}</h1>
							</div>
						</div>
						<div class="col-lg-7">

						</div>
					</div>
				</div>
			</div>
		<!-- End Hero Section -->

{% endblock %}

{% block content %}

		<div class="untree_co-section product-section before-footer-section">
		    <div class="container">
		      	<div class="row">
					{% for item in items %}
		      		<!-- Start Column 1 -->
					<div class="col-12 col-md-4 col-lg-3 mb-5">
						<a class="product-item" href="{% url "catalog:detail" item.slug  %}">
                            {% if item.image %}
							<img src="{{ item.image.url }}" class="img-fluid product-thumbnail" alt="{{item.name}}">
                                {% else %}
                                <img src="{% static "main/images/icon-image-not-found-free-vector.jpg" %}" class="img-fluid product-thumbnail">
							{% endif %}
                            <h3 class="product-title">{{item.name}}</h3>
							<h3 class="product-title">{{item.description}}</h3>
                            <h3 class="product-item-sm">Code: - {{item.display_id}}</h3>
							<strong class="product-price">Кількість на складі - {{item.quantity}}шт.</strong><br>
                            {% if  item.discount %}
                                <strong class="product-price"><del>Ціна - {{item.price}}$</del></strong><br>
							    <strong class="badge bg-danger text-white">Знижка - {{item.discount}}%</strong><br>
                                <strong class="product-price">Нова ціна - {{item.sell_price}}$</strong><br>
                            {% else %}
                                <strong class="product-price">Ціна - {{item.price}}$</strong><br>
                            {% endif %}


							<span class="icon-cross">
								<img src="{% static "main/images/cross.svg"%}" class="img-fluid">
							</span>
						</a>
					</div>
					<!-- End Column 1 -->
					{% endfor %}

		      	</div>



    <nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    <li class="page-item disabled">
      <a class="page-link" href="#" tabindex="-1">Previous</a>
    </li>
    <li class="page-item"><a class="page-link" href="#">1</a></li>
    <li class="page-item"><a class="page-link" href="#">2</a></li>
    <li class="page-item"><a class="page-link" href="#">3</a></li>
    <li class="page-item">
      <a class="page-link" href="#">Next</a>
    </li>
  </ul>
</nav>
              </div>
    	</div>

{% endblock %}

notes/main/templates/main/about.html
{% extends "main/base.html" %}
{% load static  %}


  {% block title %}
		<title> {{ title }} </title>
    {% endblock %}

{% block header %}
		<!-- Start Hero Section -->
			<div class="hero">
				<div class="container">
					<div class="row justify-content-between">
						<div class="col-lg-5">
							<div class="intro-excerpt">
								<h1>{{ title }}</h1>
								<p class="mb-4">{{ content}}. Nullam ac aliquet velit. Aliquam vulputate velit imperdiet dolor tempor tristique.</p>
								<p><a href="{%  url "catalog:index" "vsi-tovari" %}" class="btn btn-secondary me-2">Shop Now</a></p>
							</div>
						</div>
						<div class="col-lg-7">
							<div class="hero-img-wrap">
								<img src="{% static "main/images/couch.png" %}" class="img-fluid">
							</div>
						</div>
					</div>
				</div>
			</div>
		<!-- End Hero Section -->
{% endblock %}
		
{% block content %}
		<!-- Start Why Choose Us Section -->
		<div class="why-choose-section">
			<div class="container">
				<div class="row justify-content-between align-items-center">
					<div class="col-lg-6">
						<h2 class="section-title">Why Choose Us</h2>
						<p>Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate velit imperdiet dolor tempor tristique.</p>

						<div class="row my-5">
							<div class="col-6 col-md-6">
								<div class="feature">
									<div class="icon">
										<img src="{% static "main/images/truck.svg" %}" alt="Image" class="imf-fluid">
									</div>
									<h3>Fast &amp; Free Shipping</h3>
									<p>Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate.</p>
								</div>
							</div>

							<div class="col-6 col-md-6">
								<div class="feature">
									<div class="icon">
										<img src="{% static "main/images/bag.svg" %}" alt="Image" class="imf-fluid">
									</div>
									<h3>Easy to Shop</h3>
									<p>Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate.</p>
								</div>
							</div>

							<div class="col-6 col-md-6">
								<div class="feature">
									<div class="icon">
										<img src="{% static "main/images/support.svg" %}" alt="Image" class="imf-fluid">
									</div>
									<h3>24/7 Support</h3>
									<p>Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate.</p>
								</div>
							</div>

							<div class="col-6 col-md-6">
								<div class="feature">
									<div class="icon">
										<img src="{% static "main/images/return.svg" %}" alt="Image" class="imf-fluid">
									</div>
									<h3>Hassle Free Returns</h3>
									<p>Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate.</p>
								</div>
							</div>

						</div>
					</div>

					<div class="col-lg-5">
						<div class="img-wrap">
							<img src="{% static "main/images/why-choose-us-img.jpg" %}" alt="Image" class="img-fluid">
						</div>
					</div>

				</div>
			</div>
		</div>
		<!-- End Why Choose Us Section -->

		<!-- Start Team Section -->
		<div class="untree_co-section">
			<div class="container">

				<div class="row mb-5">
					<div class="col-lg-5 mx-auto text-center">
						<h2 class="section-title">Our Team</h2>
					</div>
				</div>

				<div class="row">

					<!-- Start Column 1 -->
					<div class="col-12 col-md-6 col-lg-3 mb-5 mb-md-0">
						<img src="{% static "main/images/person_1.jpg" %}" class="img-fluid mb-5">
						<h3 clas><a href="#"><span class="">Lawson</span> Arnold</a></h3>
            <span class="d-block position mb-4">CEO, Founder, Atty.</span>
            <p>Separated they live in.
            Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
            <p class="mb-0"><a href="#" class="more dark">Learn More <span class="icon-arrow_forward"></span></a></p>
					</div> 
					<!-- End Column 1 -->

					<!-- Start Column 2 -->
					<div class="col-12 col-md-6 col-lg-3 mb-5 mb-md-0">
						<img src="{% static "main/images/person_2.jpg" %}" class="img-fluid mb-5">

						<h3 clas><a href="#"><span class="">Jeremy</span> Walker</a></h3>
            <span class="d-block position mb-4">CEO, Founder, Atty.</span>
            <p>Separated they live in.
            Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
            <p class="mb-0"><a href="#" class="more dark">Learn More <span class="icon-arrow_forward"></span></a></p>

					</div> 
					<!-- End Column 2 -->

					<!-- Start Column 3 -->
					<div class="col-12 col-md-6 col-lg-3 mb-5 mb-md-0">
						<img src="{% static "main/images/person_3.jpg" %}" class="img-fluid mb-5">
						<h3 clas><a href="#"><span class="">Patrik</span> White</a></h3>
            <span class="d-block position mb-4">CEO, Founder, Atty.</span>
            <p>Separated they live in.
            Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
            <p class="mb-0"><a href="#" class="more dark">Learn More <span class="icon-arrow_forward"></span></a></p>
					</div> 
					<!-- End Column 3 -->

					<!-- Start Column 4 -->
					<div class="col-12 col-md-6 col-lg-3 mb-5 mb-md-0">
						<img src="{% static "main/images/person_4.jpg" %}" class="img-fluid mb-5">

						<h3 clas><a href="#"><span class="">Kathryn</span> Ryan</a></h3>
            <span class="d-block position mb-4">CEO, Founder, Atty.</span>
            <p>Separated they live in.
            Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
            <p class="mb-0"><a href="#" class="more dark">Learn More <span class="icon-arrow_forward"></span></a></p>

          
					</div> 
					<!-- End Column 4 -->

					

				</div>
			</div>
		</div>
		<!-- End Team Section -->

		

		<!-- Start Testimonial Slider -->
		<div class="testimonial-section before-footer-section">
			<div class="container">
				<div class="row">
					<div class="col-lg-7 mx-auto text-center">
						<h2 class="section-title">Testimonials</h2>
					</div>
				</div>

				<div class="row justify-content-center">
					<div class="col-lg-12">
						<div class="testimonial-slider-wrap text-center">

							<div id="testimonial-nav">
								<span class="prev" data-controls="prev"><span class="fa fa-chevron-left"></span></span>
								<span class="next" data-controls="next"><span class="fa fa-chevron-right"></span></span>
							</div>

							<div class="testimonial-slider">
								
								<div class="item">
									<div class="row justify-content-center">
										<div class="col-lg-8 mx-auto">

											<div class="testimonial-block text-center">
												<blockquote class="mb-5">
													<p>&ldquo;Donec facilisis quam ut purus rutrum lobortis. Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate velit imperdiet dolor tempor tristique. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer convallis volutpat dui quis scelerisque.&rdquo;</p>
												</blockquote>

												<div class="author-info">
													<div class="author-pic">
														<img src="{% static "main/images/person-1.png" %}" alt="Maria Jones" class="img-fluid">
													</div>
													<h3 class="font-weight-bold">Maria Jones</h3>
													<span class="position d-block mb-3">CEO, Co-Founder, XYZ Inc.</span>
												</div>
											</div>

										</div>
									</div>
								</div> 
								<!-- END item -->

								<div class="item">
									<div class="row justify-content-center">
										<div class="col-lg-8 mx-auto">

											<div class="testimonial-block text-center">
												<blockquote class="mb-5">
													<p>&ldquo;Donec facilisis quam ut purus rutrum lobortis. Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate velit imperdiet dolor tempor tristique. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer convallis volutpat dui quis scelerisque.&rdquo;</p>
												</blockquote>

												<div class="author-info">
													<div class="author-pic">
														<img src="{% static "main/images/person-1.png" %}" alt="Maria Jones" class="img-fluid">
													</div>
													<h3 class="font-weight-bold">Maria Jones</h3>
													<span class="position d-block mb-3">CEO, Co-Founder, XYZ Inc.</span>
												</div>
											</div>

										</div>
									</div>
								</div> 
								<!-- END item -->

								<div class="item">
									<div class="row justify-content-center">
										<div class="col-lg-8 mx-auto">

											<div class="testimonial-block text-center">
												<blockquote class="mb-5">
													<p>&ldquo;Donec facilisis quam ut purus rutrum lobortis. Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate velit imperdiet dolor tempor tristique. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer convallis volutpat dui quis scelerisque.&rdquo;</p>
												</blockquote>

												<div class="author-info">
													<div class="author-pic">
														<img src="{% static "main/images/person-1.png" %}" alt="Maria Jones" class="img-fluid">
													</div>
													<h3 class="font-weight-bold">Maria Jones</h3>
													<span class="position d-block mb-3">CEO, Co-Founder, XYZ Inc.</span>
												</div>
											</div>

										</div>
									</div>
								</div> 
								<!-- END item -->

							</div>

						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- End Testimonial Slider -->

{% endblock %}

notes/main/templates/main/base.html
{% load static  %}
{% load catalog_tags %}
<!-- /*
* Bootstrap 5
* Template Name: Furni
* Template Author: Untree.co
* Template URI: https://untree.co/
* License: https://creativecommons.org/licenses/by/3.0/
*/ -->
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="shortcut icon" href="favicon.png">

  <meta name="description" content="" />
  <meta name="keywords" content="bootstrap, bootstrap4" />

		<!-- Bootstrap CSS -->
		<link href="{% static "main/css/bootstrap.min.css" %}" rel="stylesheet">
		<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
		<link href="{% static "main/css/tiny-slider.css" %}" rel="stylesheet">
		<link href="{% static "main/css/style.css" %}" rel="stylesheet">
        {% block title %} {% endblock %}
	</head>

	<body>

		<!-- Start Header/Navigation -->
		<nav class="custom-navbar navbar navbar navbar-expand-md navbar-dark bg-dark" arial-label="Furni navigation bar">

			<div class="container">
				<a class="navbar-brand" href="{% url "main:index" %}">Furni<span>.</span></a>

				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsFurni" aria-controls="navbarsFurni" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>

				<div class="collapse navbar-collapse" id="navbarsFurni">
					<ul class="custom-navbar-nav navbar-nav ms-auto mb-2 mb-md-0">
						<li class="nav-item active">
							<a class="nav-link" href="{% url "main:index" %}">Home</a>
						</li>
						<li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">Shop</a>

                        <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">

                        {% tag_categories as category %}

                            {% for cat in category %}
                            <li><a class="dropdown-item text-white" href="{%  url "catalog:index" cat.slug %}"> {{ cat.name }} </a> </li>
                            {% endfor %}
                        </ul>
                        </li>
						<li><a class="nav-link" href="{% url "main:about" %}">About us</a></li>
						<li><a class="nav-link" href="services.html">Services</a></li>
						<li><a class="nav-link" href="blog.html">Blog</a></li>
						<li><a class="nav-link" href="contact.html">Contact us</a></li>
					</ul>

					<ul class="custom-navbar-cta navbar-nav mb-2 mb-md-0 ms-5">
						<li><a class="nav-link" href="{% url "admin:index" %}"><img src="{% static "main/images/user.svg" %}"></a></li>
						<li><a class="nav-link" href="cart.html"><img src="{% static "main/images/cart.svg" %}"></a></li>
					</ul>
				</div>
			</div>

		</nav>
		<!-- End Header/Navigation -->

        {% block header %} {% endblock %}

        {% block content %} {% endblock %}


		<!-- Start Footer Section -->
		<footer class="footer-section">
			<div class="container relative">

				<div class="sofa-img">
					<img src="{% static "main/images/sofa.png" %}" alt="Image" class="img-fluid">
				</div>

				<div class="row">
					<div class="col-lg-8">
						<div class="subscription-form">
							<h3 class="d-flex align-items-center"><span class="me-1"><img src="{% static "main/images/envelope-outline.svg" %}" alt="Image" class="img-fluid"></span><span>Subscribe to Newsletter</span></h3>

							<form action="#" class="row g-3">
								<div class="col-auto">
									<input type="text" class="form-control" placeholder="Enter your name">
								</div>
								<div class="col-auto">
									<input type="email" class="form-control" placeholder="Enter your email">
								</div>
								<div class="col-auto">
									<button class="btn btn-primary">
										<span class="fa fa-paper-plane"></span>
									</button>
								</div>
							</form>

						</div>
					</div>
				</div>

				<div class="row g-5 mb-5">
					<div class="col-lg-4">
						<div class="mb-4 footer-logo-wrap"><a href="#" class="footer-logo">Furni<span>.</span></a></div>
						<p class="mb-4">Donec facilisis quam ut purus rutrum lobortis. Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate velit imperdiet dolor tempor tristique. Pellentesque habitant</p>

						<ul class="list-unstyled custom-social">
							<li><a href="#"><span class="fa fa-brands fa-facebook-f"></span></a></li>
							<li><a href="#"><span class="fa fa-brands fa-twitter"></span></a></li>
							<li><a href="#"><span class="fa fa-brands fa-instagram"></span></a></li>
							<li><a href="#"><span class="fa fa-brands fa-linkedin"></span></a></li>
						</ul>
					</div>

					<div class="col-lg-8">
						<div class="row links-wrap">
							<div class="col-6 col-sm-6 col-md-3">
								<ul class="list-unstyled">
									<li><a href="#">About us</a></li>
									<li><a href="#">Services</a></li>
									<li><a href="#">Blog</a></li>
									<li><a href="#">Contact us</a></li>
								</ul>
							</div>

							<div class="col-6 col-sm-6 col-md-3">
								<ul class="list-unstyled">
									<li><a href="#">Support</a></li>
									<li><a href="#">Knowledge base</a></li>
									<li><a href="#">Live chat</a></li>
								</ul>
							</div>

							<div class="col-6 col-sm-6 col-md-3">
								<ul class="list-unstyled">
									<li><a href="#">Jobs</a></li>
									<li><a href="#">Our team</a></li>
									<li><a href="#">Leadership</a></li>
									<li><a href="#">Privacy Policy</a></li>
								</ul>
							</div>

							<div class="col-6 col-sm-6 col-md-3">
								<ul class="list-unstyled">
									<li><a href="#">Nordic Chair</a></li>
									<li><a href="#">Kruzo Aero</a></li>
									<li><a href="#">Ergonomic Chair</a></li>
								</ul>
							</div>
						</div>
					</div>

				</div>

				<div class="border-top copyright">
					<div class="row pt-4">
						<div class="col-lg-6">
							<p class="mb-2 text-center text-lg-start">Copyright &copy;<script>document.write(new Date().getFullYear());</script>. All Rights Reserved. &mdash; Designed with love by <a href="https://untree.co">Untree.co</a> Distributed By <a hreff="https://themewagon.com">ThemeWagon</a>  <!-- License information: https://untree.co/license/ -->
            </p>
						</div>

						<div class="col-lg-6 text-center text-lg-end">
							<ul class="list-unstyled d-inline-flex ms-auto">
								<li class="me-4"><a href="#">Terms &amp; Conditions</a></li>
								<li><a href="#">Privacy Policy</a></li>
							</ul>
						</div>

					</div>
				</div>

			</div>
		</footer>
		<!-- End Footer Section -->


		<script src="{% static "main/js/bootstrap.bundle.min.js" %}"></script>
		<script src="{%  static "main/js/tiny-slider.js" %}"></script>
		<script src="{%  static "main/js/custom.js" %}"></script>
	</body>

</html>